module.exports = {
    NOTIFICATION_HUB: process.env.NOTIFICATION_HUB || 'XXXXXXXXXX',
    NOTIFICATION_SECRET: process.env.NOTIFICATION_SECRET || 'XXXXXXXXXX',
    DOCUMENT_DB_ENDPOINT: process.env.DOC_DB_ENDPOINT || 'XXXXXXXXXX',
    DOCUMENT_DB_PRIMARYKEY: process.env.DOC_DB_PRIMARYKEY || 'XXXXXXXXXX',
    DOCUMENT_DB_DATABASE: process.env.DOC_DB_DATABASE || 'XXXXXXXXXX',
    DOCUMENT_DB_SEAT: process.env.DOC_DB_SEAT || 'XXXXXXXXXX',
    DOCUMENT_DB_BOOKING: process.env.DOC_DB_BOOKING || 'XXXXXXXXXX',
    DOCUMENT_DB_Flight: process.env.DOC_DB_Flight || 'XXXXXXXXXX',
    GET_SOLOSERVICE: process.env.GET_SOLOSERVICE || 'XXXXXXXXXX'
};
